spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for dev, use 'validate' in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:mysuperlongsecretkeythatisharder2guess1234}
  expiration: ${JWT_EXPIRATION:86400000}  # default: 1 day

server:
  port: ${PORT:8080}